/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrailsRouteImport } from './routes/trails'
import { Route as InishowenRouteImport } from './routes/inishowen'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrailsSlugRouteImport } from './routes/trails.$slug'

const TrailsRoute = TrailsRouteImport.update({
  id: '/trails',
  path: '/trails',
  getParentRoute: () => rootRouteImport,
} as any)
const InishowenRoute = InishowenRouteImport.update({
  id: '/inishowen',
  path: '/inishowen',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsSlugRoute = TrailsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inishowen': typeof InishowenRoute
  '/trails': typeof TrailsRouteWithChildren
  '/trails/$slug': typeof TrailsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inishowen': typeof InishowenRoute
  '/trails': typeof TrailsRouteWithChildren
  '/trails/$slug': typeof TrailsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inishowen': typeof InishowenRoute
  '/trails': typeof TrailsRouteWithChildren
  '/trails/$slug': typeof TrailsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/inishowen' | '/trails' | '/trails/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/inishowen' | '/trails' | '/trails/$slug'
  id: '__root__' | '/' | '/about' | '/inishowen' | '/trails' | '/trails/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InishowenRoute: typeof InishowenRoute
  TrailsRoute: typeof TrailsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trails': {
      id: '/trails'
      path: '/trails'
      fullPath: '/trails'
      preLoaderRoute: typeof TrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inishowen': {
      id: '/inishowen'
      path: '/inishowen'
      fullPath: '/inishowen'
      preLoaderRoute: typeof InishowenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails/$slug': {
      id: '/trails/$slug'
      path: '/$slug'
      fullPath: '/trails/$slug'
      preLoaderRoute: typeof TrailsSlugRouteImport
      parentRoute: typeof TrailsRoute
    }
  }
}

interface TrailsRouteChildren {
  TrailsSlugRoute: typeof TrailsSlugRoute
}

const TrailsRouteChildren: TrailsRouteChildren = {
  TrailsSlugRoute: TrailsSlugRoute,
}

const TrailsRouteWithChildren =
  TrailsRoute._addFileChildren(TrailsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InishowenRoute: InishowenRoute,
  TrailsRoute: TrailsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
